### ISSUE TITLE
老哥你把上网凭证扔github上了注意一下

### ISSUE THREAD

**Issue by voidf** [mm04315/csu-sign#1]
autoresign.pyw里

建议你把整个提交历史删掉重新推一下

**Comment by mm04315** [comment]
没事，号早销了，多谢..(◦˙▽˙◦)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月11日(周一) 晚上11:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [mm04315/csu-sign] 老哥你把上网凭证扔github上了注意一下 (Issue #1)




 
autoresign.pyw里
 
建议你把整个提交历史删掉重新推一下

**Comment by mm04315** [comment]
没事，号早销了，多谢..(◦˙▽˙◦)
